### ISSUE TITLE
GitHub action to rerun a step upon failure with specific exit-codes is doing nothing

### ISSUE THREAD

**Issue by mscheltienne** [mne-tools/mne-lsl#301]
To try to mitigate the intermittent CI failures, I wrote this small [GitHub composite action](https://github.com/mne-tools/mne-lsl/blob/main/.github/actions/retry-step/action.yaml) which should retry a step when one of the `retry_error_codes` is hit. In the case of `pytest` runs, the action is used [here](https://github.com/mne-tools/mne-lsl/blob/d8c6f87ef7a929522b4ef934efdbf35d2622294b/.github/workflows/pytest.yaml#L41-L46):

```
      - name: Run pytest
        uses: ./.github/actions/retry-step
        with:
          command: pytest mne_lsl --cov=mne_lsl --cov-report=xml --cov-config=pyproject.toml -s
        env:
          MNE_LSL_LOG_LEVEL: DEBUG
```

Thus, the exit codes on which a retry should be triggered are the [default](https://github.com/mne-tools/mne-lsl/blob/d8c6f87ef7a929522b4ef934efdbf35d2622294b/.github/actions/retry-step/action.yaml#L14) ones, `134` and `139` (Python Fatal Error, segmentation fault).
Yet, it's clearly not working. c.f. this [CI run](https://github.com/mne-tools/mne-lsl/actions/runs/10245187074/job/28339672096#step:8:828). It's actually doing _nothing_, with the runner being terminated prematurely.
